2021-01-09 20:14:32,075 ERROR: Exception on /reset_password_request [POST] [in e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\STP\stp2020_zaa\app\routes.py", line 102, in reset_password_request
    send_password_reset_email(user)
  File "E:\Study\STP\stp2020_zaa\app\email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "E:\Study\STP\stp2020_zaa\app\models.py", line 65, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2021-01-09 20:14:39,824 ERROR: Exception on /reset_password_request [POST] [in e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\STP\stp2020_zaa\app\routes.py", line 102, in reset_password_request
    send_password_reset_email(user)
  File "E:\Study\STP\stp2020_zaa\app\email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "E:\Study\STP\stp2020_zaa\app\models.py", line 65, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2021-01-09 20:19:35,711 INFO: Microblog startup [in E:\Study\STP\stp2020_zaa\app\__init__.py:45]
2021-01-09 20:39:02,561 INFO: Microblog startup [in E:\Study\STP\stp2020_zaa\app\__init__.py:45]
2021-01-09 20:39:11,683 INFO: Microblog startup [in E:\Study\STP\stp2020_zaa\app\__init__.py:45]
2021-01-09 20:39:35,103 ERROR: Exception on /reset_password_request [POST] [in e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\STP\stp2020_zaa\app\routes.py", line 102, in reset_password_request
    send_password_reset_email(user)
  File "E:\Study\STP\stp2020_zaa\app\email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "E:\Study\STP\stp2020_zaa\app\models.py", line 65, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2021-01-09 20:40:01,501 ERROR: Exception on /reset_password_request [POST] [in e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\STP\stp2020_zaa\app\routes.py", line 102, in reset_password_request
    send_password_reset_email(user)
  File "E:\Study\STP\stp2020_zaa\app\email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "E:\Study\STP\stp2020_zaa\app\models.py", line 65, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2021-01-09 20:40:12,188 ERROR: Exception on /reset_password_request [POST] [in e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\study\stp\stp2020_zaa\stp2020\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\STP\stp2020_zaa\app\routes.py", line 102, in reset_password_request
    send_password_reset_email(user)
  File "E:\Study\STP\stp2020_zaa\app\email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "E:\Study\STP\stp2020_zaa\app\models.py", line 65, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
